# Continuous delivery
name: Java CD

on:
  push:
    branches:
      - 'release/**'        # Release branches
      - workflow            # Workflow branch
      - master              # Main project branch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Assemble classes
        run: ./gradlew classes --stacktrace
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace
      - name: Generate changelog
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew generateChangelog --stacktrace
      - name: Assemble distribution
        run: ./gradlew assembleDist -x generateChangelog --stacktrace
